### ISSUE TITLE
List out mandatory plugin requirements

### ISSUE THREAD

**Issue by tunnelshade** [pwntester/codeql.nvim#1]
Thanks a ton for making this plugin. Is `nvim-lsp` a requirement for this plugin to work, then can you please call it out in the requirements.

I could only get this to work, after shifting to nightly NeoVIM & installed `nvim-lsp`.

**Comment by pwntester** [comment]
Hi!

Yep you need Neovim 0.5 at least, but nightly build is recommended if you date to use it :)

As for nvim-lsp, as stated in the README, the LSP client is not part of this plugin and you can actually use any other LSP clients. I prefer to use the built-in one but there may be people out there using vim-lsp, COC or others

**Comment by tunnelshade** [comment]
I was unable to do a runQuery without `nvim-lsp`, hence I raised this issue. I was aware of the lsp autocomplete thing which I ended up solving for a different plugin that [I use](https://github.com/tunnelshade/awesome-dots/blob/master/nvim/coc-settings.json).

**Comment by pwntester** [comment]
hmm, so I may have introduce a dependency I didnt planned for. I will check what bits of `nvim-lsp` are used by `RunQuery` and remove them so you can use any LSP client. BTW, feel free to update the README with your COC settings if you want

**Comment by pwntester** [comment]
I was not able to reproduce the issue. I uninstalled `nvim-lsp` and was able to run `RunQuery` command. Can you please send the error you get (`:messasge`)

**Comment by tunnelshade** [comment]
I think I narrowed the issue, it happens on NeoVim stable, not in nightly

```
Error detected while processing function codeql#runQuery:
line   39:
E5108: Error while calling lua chunk for luaeval(): ....config/nvim/plugged/codeql.nvim//lua/ql/queryserver.lua:2: module 'vim.lsp.rpc' not found:
	no field package.preload['vim.lsp.rpc']
        <seached_in_bunch_of_paths>
```

**Comment by pwntester** [comment]
Oh, ok, so thats not the `nvim-lsp` plugin, thats the JSONRPC client that is part of the built-in LSP client. It was added [here](https://github.com/neovim/neovim/commit/00dc12c5d8454a2d3c6806710f63bbb446076e96#diff-fe036d8f092c13feb2826e6d9daa63bf) so it may not be part of the neovim stable dist. I will add a note about Neovim 0.5 requirement. thanks!
