### ISSUE TITLE
Feature request: Make panels independent

### ISSUE THREAD

**Issue by jorgectf** [pwntester/codeql.nvim#28]
### Describe what happened (or what feature you want)

Make the extension able to create several panels (windows) with different rendered content (sarif results and query results)

### Anything else we need to know?

This feature might help in https://github.com/pwntester/codeql.nvim/issues/27.

**Comment by pwntester** [comment]
Should be implemented now along with a nice refactor that may break things, please test it!

**Comment by jorgectf** [comment]
> Should be implemented now along with a nice refactor that may break things, please test it!

@pwntester Everything works fine so far :D
