### ISSUE TITLE
Feature: fix source location

### ISSUE THREAD

**Issue by jorgectf** [pwntester/codeql.nvim#29]
When a valid database is loaded but the source does not have the usual structure, VSCode rearranges it to match the built structure.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/46056498/171926829-242aa3e9-9dc4-45a4-9f8c-526e122aae43.png">

**Comment by pwntester** [comment]
Can you please provide an example DB?

**Comment by jorgectf** [comment]
Haven't encountered this behaviour in a while. Happy to close the issue and reopen if it happens again.
