### ISSUE TITLE
Feature: Make timeout a parameter

### ISSUE THREAD

**Issue by nettrino** [pwntester/codeql.nvim#38]
## Issue Description

Can we make [timeout](https://github.com/pwntester/codeql.nvim/blob/246c6821d115bf3c659264abae5d529c126b5e3d/lua/codeql/cliserver.lua#L85) a user parameter?

### Describe what happened (or what feature you want)
Related to https://github.com/pwntester/codeql.nvim/issues/37, it would be nice to increase the timeout in case the analysis takes longer to complete.

**Comment by pwntester** [comment]
There is now a "job_timeout" config option that you can tweak, thanks for reporting the issue
