### ISSUE TITLE
NoSuchFileException from cliserver if db schema not named explicitly as expected

### ISSUE THREAD

**Issue by nettrino** [pwntester/codeql.nvim#39]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
Related to https://github.com/pwntester/codeql.nvim/issues/37, with codeql 2.10.3 on mac m1 aarch64, the dbschema created for a python project is not named `python.dbscheme` but `semmlecode.python.dbscheme`. This causes and exception to be raised and the plugin fails to load the database. Renaming the file to `python.dbscheme` yields the desired functionality

### Describe what you expected to happen

Assuming that only one `.dbscheme` is present per database, I would expect the plugin to load that by default regardless of name. If there are more than one, a prompt could allow the user to select which one should be chosen (if both cannot be loaded), or an error could be thrown.

### Tell us your environment
* nvim 0.7.2
* lunarvim stable
* Mac M1 (aarch64) Darwin mac.home 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 x86_64

**Comment by pwntester** [comment]
Please check if https://github.com/pwntester/codeql.nvim/pull/40 fixes the issue

**Comment by nettrino** [comment]
Thanks - the above is still unmerged - would you like me to test it before you actually merge or was this accidentally not merged?

**Comment by pwntester** [comment]
I thought it would be better to see whether it fixes your problem before merging. But since I ended porting some code from the VSCode extension. I think its safe to merge.
